name: Update Lambda Function

on:
  workflow_run:
    workflows: ['Run Unit Tests']
    types: [completed]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        role-to-assume: arn:aws:iam::381491881560:role/bili-reminder-lambda-execute
        aws-region: us-east-2

    - name: Build and update Lambda function
      run: make
